name: Demo Shiny App 

on:
workflow_dispatch:
schedule:


jobs:
  sync:
    runs-on: windows-latest

           
name: Sync and merge upstream repository with your current repository
  # You may pin to the exact commit or the version.
  # uses: dabreadman/sync-upstream-repo@fc5fe9952946b1daaafd9abd7fcd7e260b81ddbe
  uses: dabreadman/sync-upstream-repo@v1.3.0
  with:
    # URL of gitHub public upstream repo
    upstream_repo: https://github.com/Jenesequoi/Demo-Shiny-App
    # Branch to merge from upstream (defaults to downstream branch)
    upstream_branch: # optional, default is main
    # Branch to merge into downstream
    downstream_branch: # optional, default is 
    # GitHub Bot token
    token: ${{secrets.GITHUB_TOKEN}}
   
